### ISSUE TITLE
Project cannot clones by composer

### ISSUE THREAD

**Issue by dpolkhov** [gromver/yii2-platform-core#1]
After `php composer.phar require --prefer-dist gromver/yii2-platform-core "*"` I get 
`The requested package gromver/yii2-platform-core could not be found in any version, there may be a typo in the package name.` error. How should I fix it?

**Comment by gromver** [comment]
Hello. **gromver/yii2-platform-core** runs on top of the **yiisoft/yii2-app-basic**. You must first install the [yiisoft/yii2-app-basic](http://www.yiiframework.com/doc-2.0/guide-start-installation.html) application.

**Comment by dpolkhov** [comment]
Sure. I first installed **yii2-app-basic** but it cannot installs. 

http://joxi.ru/krD7BKJF03b0qA

**Comment by gromver** [comment]
You need to change your composer.json

"minimum-stability": "stable", => "minimum-stability": "dev",

**Comment by dpolkhov** [comment]
It works, thanks!

**Comment by gromver** [comment]
I found a bug while testing installation. Now it fixed and command:
php yii core-migrate  works fine.
You should update application (composer update), drop tables and restart php yii core-migrate command.
